sign-tag = true
shared-version = true
# Required for templates below to work
consolidate-commits = false
pre-release-commit-message = "[{{crate_name}}] version {{version}}"
tag-message = "[{{crate_name}}] version {{version}}"
tag-name = "{{crate_name}}-{{version}}"
publish = false
dependent-version = "upgrade"
pre-release-hook = ["just", "generate-readmes"]
