on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        partition: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: partition-${{ matrix.partition }}
      - name: Install just, cargo-hack, and cargo-sync-rdme
        uses: taiki-e/install-action@7769b73c2ec98c38dfcf2e18c83cfd4880c038c1 # v2
        with:
          tool: just,cargo-hack,cargo-sync-rdme
      - name: Lint (clippy)
        run: just powerset --partition ${{ matrix.partition }}/10 clippy --all-targets
      - name: Lint (rustfmt)
        run: cargo xfmt --check
      - name: Run rustdoc
        run: just rustdoc
      # Pin to a specific nightly for compatibility with cargo-sync-rdme.
      - name: Install nightly toolchain for cargo-sync-rdme
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: nightly-2025-08-31
      - name: Regenerate readmes
        run: just generate-readmes
      - name: Check for differences
        run: git diff --exit-code
    
  build-and-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # 1.81 is the MSRV
        rust-version: ["1.81", "stable"]
        partition: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: partition-${{ matrix.partition }}
      - uses: taiki-e/install-action@a9806628a7203f2a1142694d6a24a29405ae3fc4 # cargo-hack
      - uses: taiki-e/install-action@b1fb785e72add1aaabe1e13115c2292ca8925d3f # just
      - uses: taiki-e/install-action@e32179aa3c2a47939bd07439bd80ddf13f99979f # nextest
      - name: Build
        run: just powerset --partition ${{ matrix.partition }}/10 build
      - name: Run tests
        run: just powerset --partition ${{ matrix.partition }}/10 nextest run
      - name: Doctests
        run: just powerset --partition ${{ matrix.partition }}/10 test --doc
        
  build-no-std:
    name: Build on no-std
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # 1.81 is the MSRV
        rust-version: ["1.81", "stable"]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      - uses: taiki-e/install-action@d6cb41dee3c44e9ca5481d14c18240d47e8eaacc # cross
      - name: Check
        run: cross check --target thumbv7em-none-eabi --no-default-features -p iddqd

  miri:
    name: Run tests with miri (${{ matrix.aliasing-model }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Run miri under both Stacked and Tree Borrows.
        # 
        # * Stacked Borrows is the default and catches most issues,
        #   but is known to have false positives under the eventual
        #   Rust aliasing model.
        # * Tree Borrows is generally more permissive than Stacked
        #   Borrows, but is stricter for some things as well. In any
        #   case, it is likely closer to the formal model Rust is moving
        #   towards.
        # 
        # We ensure in CI that iddqd satisfies both models.
        include:
          - aliasing-model: stacked-borrows
            miri-flags: ""
          - aliasing-model: tree-borrows
            miri-flags: "-Zmiri-tree-borrows"
    env:
      RUSTFLAGS: -D warnings
      MIRIFLAGS: ${{ matrix.miri-flags }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: nightly
          components: miri
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: miri-${{ matrix.aliasing-model }}
      - uses: taiki-e/install-action@a9806628a7203f2a1142694d6a24a29405ae3fc4 # cargo-hack
      - uses: taiki-e/install-action@e32179aa3c2a47939bd07439bd80ddf13f99979f # nextest
      # Run tests for all crates containing unsafe code. Currently, that's just
      # iddqd.
      - name: Run tests
        run: cargo +nightly miri nextest run -p iddqd
      - name: Doctests
        run: cargo +nightly miri test --doc -p iddqd
